Desktop/Moordule2/members/urls.py
from django.urls import path
from .views import index, new, file

app_name="members"

urlpatterns = [
    path("", index, name="index"),        
    path("new/", new, name="new"),        
    path("<int:id>", file, name="file"),        
]

Desktop/Moordule2/moordule/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home, name="home"),
    path("members/", include("members.urls")),
]

Desktop/Moordule2/members/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    username = models.CharField(max_length=50)
    nikename = models.CharField(max_length=50)
    content = models.TextField(max_length=200, null=True)

Desktop/Moordule2/members/forms.py
from django.forms import ModelForm
from .models import Members

class MembersForm(ModelForm):
    class Meta:
        model = Members
        fields = ["username","nikename","content"]

Desktop/Moordule2/members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MembersForm
from .models import Members

# Create your views here.
def index(request):
    if request.POST:
        form = MembersForm(request.POST)
        form.save()
        
        return redirect ("members:index")

    members = Members.objects.all()
    return render(request,"index.html", { "members":members})

def new(request):
    return render (request, "new.html")

def file(request, id):
    members = get_object_or_404(Members, id= id)
    
    if request.POST:
        form = MembersForm(request.POST )
        form.save()
        
        return redirect ("members:index")

    members = Members.objects.all()
    return redirect(request, "file.html")

Desktop/Moordule2/moordule/views.py
from django.shortcuts import render, redirect

def home(request):
    return render (request, "home.html")

Desktop/Moordule2/members/templates/file.html
{% extends "layout.html" %} {% block "content" %}

<h1>建立會員資料</h1>

  Name:{{ member.username}}
  <br />
  <br />
  Nikename:{{member.nikename}}
  <br />
  <br />
  Interduce yourself:{{ member.content}}
  <br />
  <br />
  <button>返回會員資料</button>
  <form method="POST" action="{% url 'members:index' members.id %}">
    {% csrf_token %} <br />
    <button>更改會員資料</button>
  </form>

  {% endblock %}
</form>

Desktop/Moordule2/members/templates/index.html
{% extends "layout.html" %} {% block "content" %}

<h1>會員資料</h1>

<ul>
  <a href="{% url 'members:file' members.id %}">
    {% for member in members %}
    <li>{{ member.username }}</li>
    {% endfor %}
  </a>
</ul>

<a href="{% url 'members:new' %}"><button>建立會員資料</button></a>

{% endblock %}

Desktop/Moordule2/members/templates/new.html
{% extends "layout.html" %} {% block "content" %}

<h1>建立會員資料</h1>

<form method="POST" action="{% url 'members:index' %}">
  {% csrf_token %} <br />
  Name:
  <br />
  <input type="text" name="username" value="" />
  <br />
  <br />
  Nikename:
  <br />
  <br />
  <input type="text" name="nikename" value="" />
  <br />
  <br />
  Interduce yourself:
  <br />
  <br />
  <textarea name="content" value=""></textarea>
  <br />
  <br />
  <button>建立會員資料</button>
</form>

{% endblock %}